services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tor_exit_nodes
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: yourpassword
    ports:
      - "3307:3306"  # Map 3306 in the container to 3307 on the host
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  app:
    build:
      context: .
    ports:
      - "8889:8889"
    depends_on:
      - mysql
    networks:
      - app-network
    environment:
      - DOCKER=true  # Environment variable indicating Docker
      - DB_HOST=mysql
      - DB_USER=flaskuser
      - DB_PASSWORD=yourpassword
      - DB_NAME=tor_exit_nodes

volumes:
  mysql_data:

networks:
  app-network:
